version: '3.1'

services: 
    zookeeper:
        image: zookeeper
        restart: always
        hostname: zookeeper
        container_name: zookeeper
        ports: 
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

    kafka:
        image: wurstmeister/kafka
        restart: always
        container_name: kafka
        ports: 
            - "9092:9092"
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_CREATE_TOPICS: "products:1:1:compact"
        depends_on: 
            - zookeeper
        
    mongo:
        image: mongo
        restart: always
        container_name: mongo
        ports: 
            - "27017:27017"
            
    consumer:
        build: ./node-consumer
        container_name: node-consumer
        depends_on: 
            - kafka
            - mongo

    graphqlapi:
        build: ./graphql-api
        container_name: web-api
        ports:
            - "5000:5000"
        depends_on: 
            - kafka
            - mongo
            
        